# Generated by Django 6.0.2 on 2026-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='file',
            new_name='report_file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='doctor_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
