# Generated by Django 6.0.2 on 2026-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_file_report_report_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
