# Generated by Django 6.0.2 on 2026-03-04 08:50

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='aadhaar',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='problem_description',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uhid',
            field=models.CharField(default=patients.models.generate_uhid, editable=False, max_length=20, unique=True),
        ),
    ]
