# Generated by Django 6.0.4 on 2026-05-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mobile',
        ),
    ]
