# Generated by Django 6.0.4 on 2026-05-05 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_patient_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
